channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - nodejs=16.13.0
  - pip=20.1
  - pip:
      - robotframework-browser==11.1.0
      - rpaframework==12.1.1 # https://rpaframework.org/releasenotes.html

rccPostInstall:
  - rfbrowser init
